local opt = vim.opt
local g = vim.g
g.mapleader = " "
opt.hidden=true
opt.number=true
opt.updatetime=300
opt.lazyredraw=true
opt.swapfile=false
opt.tabstop=4
opt.shiftwidth=4
opt.expandtab=true
opt.smartindent=true
opt.hlsearch=false
opt.incsearch=true
opt.mouse='a'
opt.cmdheight=0
opt.splitright=true
opt.splitbelow=true
opt.backspace="indent,eol,start"
opt.ttimeoutlen=10
